import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "../utils/api";
import { Trending } from "../components/Trending";
import { NewProducts } from "../components/NewProducts";
import { AllProducts } from "../components/AllProducts";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>T-Commerce</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Trending />
        <NewProducts />
        <AllProducts />
      </main>
    </>
  );
};

export default Home;
